### ISSUE TITLE
[Feature] Dataloader

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose#15]
Possible solution:
Base64 encode the Request params and create a DataLoader for every function using the base64 encoded string as key.

**Comment by stoffern** [comment]
Possible solution:
Base64 encode the Request params and create a DataLoader for every function using the base64 encoded string as key.

**Comment by yoadsn** [comment]
Adding my 2 cents since I am thinking about this as well. I have implemented DataLoader in a hackish way under grpahql-compose before. I only implemented id searches since this is the basic usage for data-loader. But when getting something like findMany also used the same cache to resolve individual documents if a list of ids is provided. (Common used case on my implementation)

I wonder - How can we handle the case where some of the fields are selected? The cache would hold a partial doc that cannot fulfill other queries. On the other hand if we always get the entire doc there is a great potential for waste. Getting deltas of documents and doing merges seems crazy and fragile.

Your approach with the Base64 encoding would mean very little cache hits I suspect. What is your take on making DataLoader useful in a graphql app?

**Comment by stoffern** [comment]
@yoadsn looking into this now.. could you show me an example of how you did your hack?
I think that small simple apis will not require Dataloader at all as they never will have the benefit from caching at all. Thus bigger the API is it is better to have cache. And if you have a loop inside the GraphQL then basiclly someone can overload the api doing nested calls, where DL will solve the issue.

In question of how to solve it, i guess the only good solution is to fetch the entire document. But in order to see if this is for any good i need to speedtest it and see if fetching full set or making 2 calls is the fastest.
(Of course it depends on how big the document is.)

A good option would be to pass the dataloader when you compose of the models, if they are not set, then it disables dataloader for that model.

**Comment by stoffern** [comment]
@nodkz if i find it correct the only way to implement DataLoader is to put it into the `graphql-compose-mongoose` and where the TypeComposer classes are created, is that correct?

It would then be added here in an example:
https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/resolvers/findById.js#L45

I am not shure if the cache-map will be persistent between the different imports of the TC.

In order to keep the cache-map i think the only way is to send it throu the context in graphql, or am i missing something?

**Comment by yoadsn** [comment]
@stoffern it was part of some side experiment - but I'll try to layout the general approach.
DataLoader works by pulling objects by "key" or "keys".
I decided to use the "resolveParams" of as the input "key" to DataLoader and at the same time to strip our any projection to make sure I get the entire do.
Assume I have an entity called Maker

So I defined this function:
```
export const DataLoadMakers = (resolveParamsArray) => {
  let params = resolveParamsArray[0]; // I can do that only because I know the array would be of 1 resolve params. (See below, I'm using Load and not LoadMany.. again, a hack)
  params.args._ids = resolveParamsArray.map(params => params.args._id);

  // But.. we cannot allow any one requestor to get "some" of the fields.
  // this would mean hitting the cache would present partial data potentially.
  // so - we should get all fields.
  delete params.projection;

  return MakerTC.getResolver('findByIds').resolve(params);
}
```
This function would be the first argument to the DataLoader constructor and so it takes an array of "keys" and returns the objects for these keys. I use the standard resolvers from graphql-compose-mongoose.

I then define this function:
```
export function createLoadersWithFunction(fn) {
  let context = {};

  context.makers = new DataLoader(fn, { cacheKeyFn: (key) => key.args._id.toString() });

  return context;
}
```
It takes the function described above and gets a "context" object I can place on the req - to be available for graphql resolve function down the road. I also have to override the defaul "key mapping" function of DataLoader to extract the ids from the ResolveParams

Here I place the generated context on the req as an express middleware:
```
app.use((req, res, next) => {
  req.dataLoader = createLoadersWithFunction(DataLoadMakers);
  next()
});
```


Eventually, I will use the DataLoader to get data in a wrapped resolver within graphql-compose:

```
let rs = MakerTC.getResolver('findById').wrapResolve((fn) => {
  return (resolveParams) => {
    return resolveParams.context.dataLoader.makers.load(resolveParams);
  };
});
```

**Comment by stoffern** [comment]
👍 That looks good to me. As i can see from the DataLoader docs, and the setups: In order to get DataLoader to work properly it should be sendt throu from the koa/express via context to the schema.

I dont think that setting up a wrapper will work, as the cache is not saved between all TC imports you will have in the schema.

I am currently building a solution now that will work, but it is a small framework based on koa2 server, buildt on ES6 and classes. it parses the config, models, routes and template folder and starts up a server with all needs automaticly. All the user needs to do is to edit config and the schema.js

**Comment by stoffern** [comment]
I may need to correct that as the nodejs enviroment caches the modules that are imported. and doing multiple imports in seperate files should return the same TC.. so i think that DataLoader on a wrapper would work :) composeWithDataLoader()..

**Comment by nodkz** [comment]
@stoffern yep, should work. Somehow, in the same way, works graphql-compose-relay plugin, which populates map of model names with findById resolvers for obtaining data via `node` interface/root-field.

**Comment by stoffern** [comment]
@nodkz 👍 i am halfway to completion already 😉

**Comment by stoffern** [comment]
@yoadsn will relase it tomorrow, when i am complete. Right now i have tested findById, findByIds, and connection and works like a charm.

```
  --> POST /graphql? 200 1,947ms 1.64mb
vs
  --> POST /graphql? 200 6,700ms 1.64mb

**Comment by stoffern** [comment]
@nodkz is there a way to access some sort of function after everything is run on the schema?
right now it caches every request forever, need to fire up a `clear` after request is complete.

**Comment by nodkz** [comment]
@stoffern right now no such method. And for now I don't now how to implement it.

--

Better way will be to use `context` and put dataloaders there. So it will be removed by GC after query execution.

Eg.
```js
// server.js
import { getFreshDataLoaders } from 'graphql-compose-data-loader';

app.get('/graphql', graphqlHTTP(req => ({
  schema: GraphQLSchema,
  graphiql: true,
  context: {
    userId: req.userId,
    admin: req.admin,
    req,
    gqcDataLoaders: getFreshDataLoaders(),
  },
})));
```

So if we go such way, in future we can create method `addToContext('key', 'data')` to storage and in [buildSchema](https://github.com/nodkz/graphql-compose/blob/master/src/storage.js#L53) make `wrapResolve` on `Query` and `Mutation` types (if these root types do not support resolve method, we can traverse by its fields and wrap their resolve methods). So we will find good way.

But for now pass it explicitly via context as in example above.

**Comment by stoffern** [comment]
@nodkz yeah thats what i had in mind when i started..
but i have now created a `composeWithDataLoader(typeComposer, {cacheExpiration: 3000})`
and it works pretty well.. it is the only solution besides going all the way throu the context..

I seem to have huge wins on the query times.. 😮 🚀 
Will post it tomorrow when i have it completed.

**Comment by stoffern** [comment]
Added repo here.. not complete yet and dont have the time to do it today 😫 
To little time, anyways i have published the repo as a work in progress..

**Comment by nodkz** [comment]
@stoffern awesome!
Try to review it next week. At first look, we cannot wrap `findMany` and `connection` resolvers cause it can be fetched not only by `_id`. Only if we using them for DataLoader population, but it looks a little bit wired.

**Comment by stoffern** [comment]
@nodkz i have solved that by creating a unique hash tag of the resolveParams object to be a key in the DataLoader. This means that requesting the same `findMany` in multiple requests or spammers that want to attack the API would resolve it to a cached value..

I may not make findMany requests go faster, but it will help secure the API to be more stable agains bigger attacks and spammers.
😉

**Comment by stoffern** [comment]
Solved https://github.com/stoffern/graphql-compose-dataloader
😉

**Comment by stoffern** [comment]
Now used in production and works stable with good RP times 👍

**Comment by nodkz** [comment]
Awesome work! 🎉

> @nodkz i have solved that by creating a unique hash tag of the resolveParams object to be a key in the DataLoader. This means that requesting the same findMany in multiple requests or spammers that want to attack the API would resolve it to a cached value..
>
> I may not make findMany requests go faster, but it will help secure the API to be more stable agains bigger attacks and spammers.

I think, that it should be a task of another plugin. With time (when will be not only mongoose) we may got a problem with such mixed logic. 

Anyway let keep it as is for now.

**Comment by yoadsn** [comment]
Hi, I have written up a short comment on the source I have seen so far.
https://github.com/stoffern/graphql-compose-dataloader/issues/1
Hope this could be of help to the progress.
Thank you!

**Comment by nodkz** [comment]
Wow, what I just find!

https://twitter.com/nodkz/status/840614468761636864

**Comment by yoadsn** [comment]
@nodkz Diving in just now! Really hope this is a good approach!

**Comment by stoffern** [comment]
Looks valid to me, but there will be a problem implementing it directly with `graphql-compose` as it it also uses `rawQuery` and some additional fields outside default GraphQL resolvers.

In order to implement it into the `graphql-compose` we would need to rewrite a small part of the code.
