### ISSUE TITLE
[Feature] print schema for relay

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose#17]
integrate schema updater in composer?

``` js
GQC.printSchema('path')
```

**Comment by nodkz** [comment]
I do not understand idea of this feature. Can you provide additional explanation?

**Comment by stoffern** [comment]
integrating introspectionQuery and printSchema: 
https://github.com/nodkz/graphql-compose-examples/blob/master/buildSchema.js

**Comment by nodkz** [comment]
Closed due related issue: https://github.com/nodkz/graphql-compose/issues/27
