### ISSUE TITLE
[Example] Geo query

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose#19]
@nodkz 
Could you help me out and add a example for a connection+geo query example?

```
{
  viewer{
    feed(first: 10, longitude: 10.000, latitude: 20.000){
      edges {
        node {
          id
        }
      }
    }
  }
}
```

Guess this will be complex as you can not have a raw mongodb query `near` ?

**Comment by nodkz** [comment]
Closed due new `filter args proposal` in #22
