### ISSUE TITLE
[Feature] Add method `Resolver.wrapFilter` which allows creating custom filters

### ISSUE THREAD

**Issue by nodkz** [nodkz/graphql-compose#22]
Proposal of setting custom `filter` args, that affect on query:

```js
somehowAddTypeToSchema(`input IntRange {
  gt: Int
  lt: Int
}`);
somehowAddTypeToSchema(`input LonLat {
  lng: Float!
  lat: Float!
}`);


ViewerTC.addField(
  'shopList',
  ShopTC
    .getResolver('findMany')
    .addFilterArg({
      name: 'nameRegexp',
      type: 'String', // also can be 'Int Float Boolean ID String! [String] AnyNamedType' 
      description: 'Search by regExp',
      query: (query, value, resolveParams) => {
        query.name = new RegExp(value, 'i');
      },
    })
    .addFilterArg({
      name: 'priceLH',
      type: 'IntRange', // example of NamedType
      description: 'Search by price range',
      defaultValue: { gt: 0, lt: 100},
      query: (query, value, resolveParams) => {
        if (value.gt || value.lt) {
          const price = {};
          if (value.gt) price.$gt = value.gt;
          if (value.lt) price.$lt = value.lt;
          query.where({ price });
        }
      },
    })
    .addFilterArg({
      name: 'geo',
      type: 'LonLat', // example of NamedType
      description: 'Search by 5km radius (`2dsphere` index on `geo` field)',
      query: (query, value, resolveParams) => {
        if (value.lng || value.lat) {
          query.where({ 
            geo: {
              $nearSphere: {
                 $geometry: {
                    type: "Point",
                    coordinates: [ value.lng, value.lat ]
                 },
                 $maxDistance: 5000
              }
           }
          });
        }
      },
    })

    // Example of previous proposal version
    // .addFilterArg({
    //   args: {
    //     someField: {
    //       type: String,
    //       description: 'Search by regExp',
    //     },
    //     priceLow: {
    //       type: String,
    //       description: 'Search by priceLow',
    //     },
    //     priceHight: {
    //       type: String,
    //       description: 'Search by priceHight',
    //     }
    //   },
    //   query: (query, { someField, priceLow, priceHight }, resolveParams) => {
    //     if (someField) {
    //       query.where({ someField: new RegExp(someField, 'i') });
    //     }
    //     
    //     if (priceLow || priceHight) {
    //       const price = {};
    //       if (priceLow) {
    //         price.$gt = priceLow;
    //       }
    //       if (priceHight) {
    //         price.$lt = priceHight;
    //       }
    //       query.where({ price });
    //     }
    //     
    //     return query;
    //   }
    // })

    .getFieldConfig()
);
```

#### Proposal above requires some additional improvements
`somehowAddTypeToSchema` should put created types to some "type-cache" `type TypeMap = { [typename: String]: GraphQLObjectType }`. Types created via TypeComposer also should be placed to this type-cache.

`fieldConfig.type` will accept a string with typeName (in addition to GraphQLObjectTypes). Eg. `Int Float Boolean ID String! [String] AnyNamedType Json`.

PS. This is not a final proposal and can be updated.

**Comment by nodkz** [comment]
Method `somehowAddTypeToSchema` completed. You may see how it works in tests https://github.com/nodkz/graphql-compose/blob/type_mapper/src/__tests__/typeMapper-test.js

**Comment by nodkz** [comment]
This proposal realized in `graphql-compose@0.1.1` and `graphql-compose-mongoose@1.2.1`.

Code example of filtering name by RegExp:
https://github.com/nodkz/graphql-compose-examples/blob/master/examples/northwind/models/product.js#L38,L49

Live demo: 
http://graphql-compose.herokuapp.com/northwind/?query=%0A%7B%0A%20%20viewer%20%7B%0A%20%20%20%20productList(filter%3A%20%7B%20nameRegexp%3A%20%22of%22%20%7D)%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20

**Comment by nodkz** [comment]
cc @andrewhickey

**Comment by stoffern** [comment]
holy smokes, this is great @nodkz

**Comment by nodkz** [comment]
Add example for built-in mongodb **fulltext search with stemming and weights**.
See first comment.

This search requires new `graphql-compose-connection@>=2.0.0` with fallback sorting algorithm. See changes in [proposal](https://github.com/nodkz/graphql-compose-connection/issues/3)
Also update `graphql-compose@>=1.2.2` and `graphql-compose-mongoose@>=1.3.1`.

**Comment by nodkz** [comment]
I'm absolutely disappointed by MongoDB text search. So I'm starting to develop a new plugin `graphql-compose-elasticsearch`.

Keep in touch. 

PS. @stoffern sorry dude, but I again delay your documentation PR. Please understand me, that I don't want to publish docs for unstable API. 😉

**Comment by stoffern** [comment]
@nodkz no worries 😉 i have been offline lately aswell, alot of traveling and work have taken up my time.

What is wrong with Mongo DB text search?

**Comment by andrewhickey** [comment]
I'm guessing that it's because it will only search on whole words or sentences. Makes it useless for searching for fields that only contain small amount of text.

{ name: "Andrew" }

only matches with search string "Andrew" where it'd be nice if it matched on "An", "And" or some configurable stem length.

That's my frustration with it anyway!

**Comment by stoffern** [comment]
@andrewhickey you cannot search with regex? 😟

**Comment by andrewhickey** [comment]
Yeah mostly, that was just a simplified example to demonstrate the stemming issue. I've been trying to use it to search across multiple fields and on documents with loosely defined schemas.

**Comment by stoffern** [comment]
wierd, this should work:

```js
db.users.find({name: /a/})  //like '%a%'
db.users.find({name: /^pa/}) //like 'pa%' 
db.users.find({name: /ro$/}) //like '%ro'
```

**Comment by andrewhickey** [comment]
it does, but if your schema looks like this 
```
{
  fname: "Andrew",
  username: "Andrew",
  nickname: "Andy",
  metadata: {
    userCustomField: "Andrewhickey"
  }
}
```
with an index of `{ '$**': 'text' }`
then it's hard to search with regex across all the fields (though not impossible for sure!)

**Comment by stoffern** [comment]
@andrewhickey check gitter :)

**Comment by nodkz** [comment]
@stoffern  @andrewhickey  
The MongoDB full-text search is an incredible dump.
If you provide more and more words it returns more and more results. Cause use OR operator for provided words. But it's a not desired result for modern search engines. And if you want to build some complex text query it may be very costly or impossible at all.

I dived into MongoDB's Jira and read all search-related issues. So many of them not closed more than several years. For example, see on this old closed issue [2 years is opened this problem with UTF-8 collation. In the 2010 year it was normal, but in 2015 it is abnormal [SERVER-8423]](https://jira.mongodb.org/browse/SERVER-8423). And I didn't found that solving text-search needs will be changed in the near future. Even though announced facet search via aggregation in MongoDB v3.4. 

In 2015 MongoDB became billion dollars unicorn but their giant ideas become focused definitely not on the development of new features (eg. text-search). I'm [working](https://university.mongodb.com/certified_professional_finder/#country=KZ&expertise=dual) with MongoDB from the 2010 year (v1.6) and still love this DB and use in production. But the last few years have seen how they slow down.
cc @erh @dwight 

---

Anyway, we should somehow close our needs today. And after some investigation, I found that **ElasticSearch** is a good solution for modern search. Today it supports out of the box:
- complex search queries (AND, OR, NESTING, CONDITIONAl WEIGHTS)
- stemming (a bunch of different analyzers (filters + tokenizers)
- suggestions
- did you mean? (for misprints)
- facets
- percolator search (check meet a doc to the list of persisted queries or not) 
- good scalability (sharding, replication) and is available on AWS as a service
- [kibana](https://www.elastic.co/products/kibana) for data visualization (much better than Compass from MongoDB)

**WHOA, I what all this in MongoDB! But not in this year, and maybe not in the next 😟.**

PS. How I understood, ElasticSearch team try to eat a piece of pie from a NoSQL database market. Their renaming to [elastic.co](https://www.elastic.co/) just confirms my guess.

PSS. So for fast getting down and dirty with ElasticSearch, I recommend watching this amazing video: https://www.youtube.com/watch?v=52G5ZzE0XpY

**Comment by stoffern** [comment]
Could this be of any help? 
https://github.com/zackiles/elasticsearch-odm

**Comment by nodkz** [comment]
@stoffern Yep, thanks ;)
It uses `elasticsearch@8.0.1` (last version is `12.0.1`) but it is not a problem. Cause I'll write something new that will combine experience from [elasticsearch-odm](https://github.com/zackiles/elasticsearch-odm) and [elasticsearch-graphql](https://github.com/nordsimon/elasticsearch-graphql).

**Comment by nodkz** [comment]
Added new feature: cloning resolver with cloning its argument. Very useful if you want to create your own resolver from standard and modify its argument (eg. `filter`) keeping untouched this argument in the standard resolver.

---

Also from `graphql-compose@1.11.0` available method `Resolver.wrapCloneArg` which allows to clone argument type and extend it:
```js
// from `findMany` creating new 'findManyForAdmins' resolver and extending only its `filter` argument
ShopTC.setResolver('findManyForAdmin',
  ShopTC.get('$findMany').getResolver('findMany')
  .wrapCloneArg('filter', 'FilterFindManyShopAdminInput')
  .addFilterArg({ ... })
);

// from `findMany` creating new 'findManyForUser' resolver and removing some fields from only its `filter` argument
ShopTC.setResolver('findManyForUser',
  ShopTC.get('$findMany').getResolver('findMany')
  .wrapCloneArg('filter', 'FilterFindManyShopUserInput')
);
ShopTC.('$findManyForUser.@filter').removeField(['price', 'geo', 'tags']);

// so `findMany` resolver will have `filter` arg with type FilterFindManyShopInput
// `findManyForAdmin` resolver will have another extended `filter` arg with type FilterFindManyShopAdminInput
// `findManyForUser` resolver will have cutted `filter` arg with type FilterFindManyShopUserInput
```

**Comment by yoadsn** [comment]
@nodkz Thank you!
I am trying to understand from the code examples the usage of the new feature.
Does that mean that without using this `wrapCloneArg` you cannot extend the standard `filter` without changing the original resolver? I Think I used `addFilterArgs` in the past before and not seen this behavior..
For example doing this:
```
tc.get('$findMany').addFilterArg({
  name: 'slugs',
  type: '[String]',
  query: (query, value, resolveParams) => {
    query.slug = { $in : value }
  }
});
```
Changes the original findMany ?

btw -
```
ShopTC.get('$findMany').getResolver('findMany')
```
Why do you need here both the `get` and the `getResolver` - don't they do the same?

**Comment by nodkz** [comment]
@yoadsn 
Yep `ShopTC.get('$findMany')` is the same to `ShopTC.getResolver('findMany')`. Thanks for your notice, I'm fixed my typos above.

> Does that mean that without using this wrapCloneArg you cannot extend the standard filter without changing the original resolver? I Think I used addFilterArgs in the past before and not seen this behavior..

You can extend filter Type. But when you use resolver in several places in your schema (my aim was to have different filters for users (in Viewer) and admins (in Adm)). So when I add new filters for admins, it became visible for regular users (they does not work for user, but were visible in schema). Cause one graphql type used for `filter` arg in both resolvers. So `wrapCloneArg` just return new Resolver with clonned `filter` type, and then you may safely add new filters.

**Comment by stoffern** [comment]
@nodkz When talking about mongoose and elasticsearch..
https://github.com/mongoosastic/mongoosastic

**Comment by nodkz** [comment]
Thanks. I'm currently working with it. Also found it today and try to play with it.
But I did not found how to work with facets: https://github.com/mongoosastic/mongoosastic/issues/282
Anyway it looks very promising.

**Comment by stoffern** [comment]
I really want to look into that also. But i have to admit i dont know elasticsearch and how it works, only that it is good!.

Have a app project now (working on it for 1 year) and it kills all my time to develop any other new stuff.. 😢  Altho soon finished with it so i can play around again 😉 

I will come back stronger, and make some plugins for `graphql-compose` as soon as i can

**Comment by nodkz** [comment]
@stoffern same thing 😉

And I have not another way, should crack it asap. Cause elastic from the current week is my prioritized feature in our internal app. So one week or two (hope not longer) and we will get one more cool plugin.

**Comment by yoadsn** [comment]
Two weeks ago, had to integrate with a search quickly - Eventually used the simpler Azure-Search service since it removed the need for hosting ES and I get free hosting credits on Azure.
Will switch to ES if/when you guys make a progress so I can also contribute to the plugin and testing.

**Comment by nodkz** [comment]
@yoadsn will be cool, if it possible, to publish your solution as `graphql-compose-azure-search` plugin.

I'm definitely will use `elastic-search` with https://github.com/mongoosastic/mongoosastic it gives me freedom of choice (AWS ES, elastic cloud, or docker containers anywhere). I'm read docs, made some tests on it, but landed more important things so in a couple of days I'll finish them and come back to ES plugin.

Right now I do not imagine how it should work. So when something testable will be ready, I let you know.

**Comment by stoffern** [comment]
@nodkz i cant seem to get `addFilterArg` working when i want a regex search over multiple fields.

example:
```js
.addFilterArg({
    name: 'search',
    type: 'String', // also can be 'Int Float Boolean ID String! [String] AnyNamedType' 
    description: 'Search by regExp',
    query: (rawQuery, value, resolveParams) => {
      rawQuery = {
        $or: [
          { firstName: new RegExp(value, 'i') },
          { lastName: new RegExp(value, 'i') },
          { email: new RegExp(value, 'i') }
        ]
      }
    },
  })
```
anything i am doing wrong?

**Comment by nodkz** [comment]
Should work. Maybe it overlapped with other criterias. Try to debug it with:
```js
  .wrapResolve((next) => (rp) => {
    const r = next(rp);
    console.log('RawQuery:', rp.rawQuery);
    console.log('Mongoose query:', rp.query);
    return r;
  })
```

**Comment by stoffern** [comment]
just to be clear:
```js
{
  users: UsersTC.get('$connection')
  .addFilterArg({
    name: 'search',
    type: 'String', // also can be 'Int Float Boolean ID String! [String] AnyNamedType' 
    description: 'Search by regExp',
    query: (rawQuery, value, resolveParams) => {
      rawQuery = {
        '$or': [
          { firstName: new RegExp(value, 'i') },
          { lastName: new RegExp(value, 'i') },
          { email: new RegExp(value, 'i') }
        ]
      }
    },
  })
  .wrapResolve((next) => (rp) => {
    const r = next(rp);
    console.log('RawQuery:', rp.rawQuery);
    console.log('Mongoose query:', rp.query);
    return r;
  })
}
```
results in:
```
RawQuery: {}
Mongoose query: undefined
```

**Comment by stoffern** [comment]
It may have something to do with it is a `connection`

**Comment by nodkz** [comment]
The connection is a combination of two resolvers and can be inspected in such way: 
```js
  .wrapResolve((next) => (rp) => {
    const r = next(rp);
    console.log(rp.rawQuery);
    console.log('FindManyResolver', rp.findManyResolveParams);
    console.log('CountResolver', rp.countResolveParams);
    return r;
  })
```

**Comment by nodkz** [comment]
How to compose MongoDB and ElasticSearch via GraphQL:
- data sync
- indexing
- search
- relations
- api
https://github.com/nodkz/graphql-compose-elasticsearch/issues/21
