### ISSUE TITLE
Exposed GraphQL types

### ISSUE THREAD

**Issue by yarax** [nodkz/graphql-compose#27]
Do you consider possibility to generate pure types on GraphQL language?

**Comment by nodkz** [comment]
With pleasure add anu usefull pure types.

Existed types: https://github.com/nodkz/graphql-compose/tree/master/src/type
`missingType` and `missingTypeResolver` will be removed, they are rudiments from first version.

Grapql-compose has build-in type constructor with following types: https://github.com/nodkz/graphql-compose/blob/master/src/typeMapper.js#L112-L118
 ```js
// creation of OutputObjectType
const LonLatTC = TypeComposer.create(`
  type LonLat {
    lat: Float
    lon: Float
  }
`);

// creation of InputObjectType
const LonLatITC = TypeComposer.create(`
  input LonLatInput {
    lat: Float! // required field
    lon: Float!
  }
`);

// also type converter works on field definition via `create`, `addFields`, `setFields` and others:
const PlaceTC = TypeComposerCreate({
   name: 'Place',
   fields: {
      point: 'LonLat!', // we can use created types via `TypeComposer.create`
      filials: '[LonLat]',
   },
});

PlaceTC.addFields({
  name: 'String!',  
  // or
  name: {
     type: 'String!',
     description: 'Place name',
  },
  // or
  name: {
     type: new GraphQLNonNull(GraphQLString),
  }
  
  // other fields
  commenstConnection: CommentsTC.getResolver('connection'),
  commenstConnection: CommentsTC.get('$connection'), // the same as previous line
});
```

**Comment by yarax** [comment]
Can I for example generate pure GraphQL type from Mongoose schema?

**Comment by nodkz** [comment]
Of course
```js
const UserTC = composeWithMongoose(UserModel);
UserTC.getType(); // returns GraphQLObjectType
UserTC.getInputType(); // return GraphQLInputObjectType, eg. for args
UserTC.get('fieldWithNesting').getType(); // get GraphQL type of nestedField
UserTC.get('fieldWithNesting.subNesting').getType(); // get GraphQL type of nested nested type
```

**Comment by yarax** [comment]
Cool, thanks

**Comment by yarax** [comment]
I looked at the code, but it seems like getType() is a js implementation of a type, but I meant GraphQL type language http://graphql.org/learn/schema/

**Comment by nodkz** [comment]
I think that it should do graphql-js.
Open [PR](https://github.com/graphql/graphql-js/pull/558) to expose `printType` method.

If this PR will be accepted, you can print type in such way:
```js
import { printType } from 'graphql-js';

const UserTC = composeWithMongoose(UserModel);
printType(UserTC.getType()); // returns type in `GraphQL Schema language` form.
```

But right now you may use something like this:
```js
const UserTC = composeWithMongoose(UserModel);
UserTC.getFieldNames(); // returns just array of field names

// or write some helper (not tested)
function printType(TC) {
  const fields = TC.getFields();
  Object.keys(fields).forEach((fieldConfig, fieldName) => {
    console.log(fieldName, fieldConfig.type.toString());
  })
}
```

**Comment by nodkz** [comment]
I'm not so YAGNI like Lee, so you may open PR and add `TypeComposer.printType` method.
Thanks.

**Comment by nodkz** [comment]
By the way, the same method needs for InputTypeComposer.
After that you may do such things:
```js
UserTC.printType();
UserTC.get('someComplexField.subField').printType();
UserTC.get('$findMany.@filter').printType(); // get resolver `findMany` and print type of `filter` arg
```

I think that `printType()` is good enhancement for `graphql-compose` and easy way to became a contributor 😉

**Comment by nodkz** [comment]
`printType` method now exposed in `graphql@0.8.1` - [method source code](https://github.com/graphql/graphql-js/blob/master/src/utilities/schemaPrinter.js#L139).

Now you can print type such way:
```js
import { printType } from 'graphql-js';

const UserTC = composeWithMongoose(UserModel);
printType(UserTC.getType()); // returns type in `GraphQL Schema language` form.
printType(UserTC.get('$findMany.@filter').getType());
```

@yarax do you want to add `printType` method to `TypeComposer` and `InputTypeComposer`?
For simplifying above code to:
```js
const UserTC = composeWithMongoose(UserModel);
UserTC.printType(); // returns type in `GraphQL Schema language` form.
UserTC.get('$findMany.@filter').printType();
```

**Comment by yarax** [comment]
Cool! No, I think now when it's official method there is no need to wrap it over

**Comment by nodkz** [comment]
I think that `TypeComposer.printType()` should have `deep` argument. That prints all types (for args and complex types) which used for type in TypeComposer.

Ok, let keep this as is, until get real request for this feature.
