### ISSUE TITLE
directly create a document from a type

### ISSUE THREAD

**Issue by atalebagha** [nodkz/graphql-compose#33]
Let's say I have `UserTC`.  I know i can do `UserTC.find({ _id: id }).exec(...)`.  Can I create a document/record the same way.  Like `UserTC.create(req.body).save()` ?

**Comment by stoffern** [comment]
Please spesify a little more what you want to do.
Modifications should be put as `mutations` and not `query`.

```js
export const RootMutationTC = GQC.rootMutation()

RootMutationTC.addFields({
  createUser: UsersTC.get('$createOne'),
  updateUser: UsersTC.get('$updateById'),
})

const graphqlSchema = GQC.buildSchema()
export default graphqlSchema
```

**Comment by stoffern** [comment]
@atalebagha if this answers your question, please close the issue 😉

**Comment by atalebagha** [comment]
Thanks @stoffern.

Sorry I didn't make myself clear, I wanted to directly create a document within the code, not using a graphql mutation api call.

**Comment by stoffern** [comment]
Ah yes..

Users table
```js
var UsersSchema = new mongoose.Schema({
  firstName: { type: String },
  lastName: { type: String },
  email: { type: String },
}, {collection: 'Users' }
)
export const Users = mongoose.model('Users', UsersSchema)
export const UsersTC = composeMongoose(Users)
```
where you want to execute code
```js
import {Users} from './Users'

Users.find()
Users.findById()
Users.whatever()..
```
