### ISSUE TITLE
Rename addResolver key

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose#34]
Rename kind to type inside addResolver?
@nodkz would that make more sense?

**Comment by nodkz** [comment]
This field was created for `graphql-compose-relay`, if it found mutation then wrap args in `input` and adds `clientMutationId`.

But I think to change the behavior of `graphql-compose-relay`, that it should be run only on schema, not on every model. It's simplify examples and `wrapResolve` definitions, cause it bring a differ in args with `input`; depends if used `graphql-compose-relay` on model or not.

So maybe `kind` prop is excessive.

**Comment by stoffern** [comment]
I think it is ok to define what kid of resolver we are dealing with.
Just think it would be easier to understand the key `type` instead of `kind` ? 😉 

There may be other sub repos that need to know what kind of resolver it is aswell.

**Comment by nodkz** [comment]
`kind` is better name, cause this is a standard name for AST node type. Resolvers may have only `query`, `mutation` kinds right now.

BTW I want to rename `outputType` in resolvers to `type` (cause resolvers is a partial graphql `fieldConfig`. And fieldConfig uses `type` property name for GraphQL type). So name `type` is reserved 😜

**Comment by nodkz** [comment]
**Changes in @1.7.0**

Renamed properties/options in **`Resolver`**:
* `outputType` -> `type`

Renamed methods in `Resolver`:
* `getOutputType` -> `getType`
* `setOutputType` -> `setType`
* `wrapOutputType` -> `wrapType`

All old names are compatible right now. But in next releases (after updating `graphql-compose-mongoose` and other plugins) will warn to console that used deprecated methods/option.
