### ISSUE TITLE
What Phase

### ISSUE THREAD

**Issue by atalebagha** [nodkz/graphql-compose#36]
Is this project still in Pre Production?  If not when do you plan on moving it towards production?

**Comment by nodkz** [comment]
The API is almost stable. Will be small changes but not scary (would be deprecation messages at build steps with how-to-fix).
If you want to use it for spaceship or health care applications, I'll recommend you to wait a half year, maybe year 😉 Who knows, maybe it will have enterprise support in future.

But if you have a more simple app and have strong knowledge of GraphQL internals, fill free to use it in production. Right now the community of this lib just several peoples. So need time that `graphql-compose` became really production ready. But it does not stop me to use this lib as a core module of my internal app right now. BTW GraphQL itself become production ready in September 2016.
 
If your server is build with nodejs and mongoose (MongoDB) better lib than `graphql-compose-mongoose` you will not find.

I have not enough time to write documentation right now. So if you do not afraid to dive into the source code of this lib, reread open and closed issues you may found a huge amount of cool things that help to build complex graphql schemas.
---
> Is this project still in Pre Production? 
Yep, still in Pre Production.

> If not when do you plan on moving it towards production?
The community should decide when it becomes production ready. I can not alone make it production ready without feedback and community help.

**Comment by stoffern** [comment]
It is very stable, the API is working without bugs. i have used almost 100% of the functions in a single API.

Altho i think that getting the documentation in place, and some polish of the API would be a good idea 😉
