### ISSUE TITLE
.wrapResolve for fields

### ISSUE THREAD

**Issue by atalebagha** [nodkz/graphql-compose#39]
Is there anyway to create rules for changing fields

For example:

order.js
```javascript
const orderSchema = new Schema({
  orderId: String,
  status: {
    type: Number,
    enum: [0,1,2,3,4]  // 0 = pending, 1 = processing, 2 = en route, 3 = delivered, 4 = cancelled ...
  },
  deliveryAddress: String,
}
```

I want to make a rule that if status > 1, the deliveryAddress cannot be changed in the mutation `orderUpdate:  OrderTC.getResolver('updateById')`.  Another rule is status can never move down, if has been moved to `1` it cannot go back to `0` etc.  

Thanks!

**Comment by stoffern** [comment]
Create a custom resolver. example would be:

In your Orders.js
```js
OrderTC.addResolver({
  name: 'orderUpdate',
  kind: 'mutation',
  outputType: TypeComposer.create({
    name: 'OrderUpdatePayload',
    fields: {
      recordId: 'ID',
      record: OrderTC,
    },
  }), 
  args: {
    id: 'String',
    status: 'Int',
  },
  resolve: async ({ args, context }) => {
    if (args.status <= 1) throw new Error('cannot change this status')
    if (args.status > 1){
      let status = args.status
      if (status = 0)  throw new Error('status cannot go back')
      let order = await Order.findById(args.id)
      order.status = args.status
      await order.save()
      return {
         recordId: order._id,
         record: order,
      }
    }
  }
})
```
in schema.js
```js
orderUpdate: OrderTC.getResolver('orderUpdate')
or 
orderUpdate: OrderTC.get('$orderUpdate')
```

**Comment by stoffern** [comment]
Feed like we should get the documentation in place asap..

**Comment by stoffern** [comment]
PS: if you are using Relay you should use relay id and not MongoDB ids

**Comment by joepistritto** [comment]
Hi, this is useful info. However, can you show examples of how you would do the actual mongoose calls? In the code above, would you do something like:

`
resolve: async ({args, context}) => {
  if (args.status <= 1) throw new Error('cannot change this status');
  let order = await Order.findByIdAndUpdate(args.id, {$set: {status: args.status}}, {new: true});
  return {
    recordId: order._id;
    record: order
  }
}
`

Or instead of doing the mongoose findByIdAndUpdate call, is the best practice to wrap the updateById resolver?

Also, if I want to use Relay, how do I get the relay ID and not the MongoDB IDs?

**Comment by nodkz** [comment]
@joepistritto your example is correct.
Less code typing is better. So if you manually build resolver as above, better to use mongoose query. 
Resolver wrapping in some cases helps to reduce your code, in other not. So up to you what to use.

`graphql-compose-relay` should automatically take `recordId` and create `nodeId` field with Relay global id in the mutation payload. Example of mutation [without nodeId](http://graphql-compose.herokuapp.com/user/?query=%0Amutation%20%7B%0A%20%20userCreate(record%3A%20%7B%0A%20%20%20%20name%3A%20%22My%20Name%22%2C%0A%20%20%20%20age%3A%2024%2C%0A%20%20%20%20gender%3A%20ladyboy%2C%0A%20%20%20%20contacts%3A%20%7B%0A%20%20%20%20%20%20email%3A%20%22mail%40example.com%22%2C%0A%20%20%20%20%20%20phones%3A%20%5B%0A%20%20%20%20%20%20%20%20%22111-222-333-444%22%2C%0A%20%20%20%20%20%20%20%20%22444-555-666-777%22%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%7D)%20%7B%0A%20%20%20%20recordId%0A%20%20%20%20record%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20age%0A%20%20%20%20%20%20gender%0A%20%20%20%20%20%20contacts%20%7B%0A%20%20%20%20%20%20%20%20email%0A%20%20%20%20%20%20%20%20phones%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20someMixed%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20&operationName=undefined) [[code](https://github.com/nodkz/graphql-compose-examples/blob/master/examples/user/models/user.js#L46)] and [with nodeId](http://graphql-compose.herokuapp.com/userForRelay/?query=%0Amutation%20%7B%0A%20%20userCreate(input%3A%20%7B%0A%20%20%20%20clientMutationId%3A%20%221%22%2C%0A%20%20%20%20record%3A%20%7B%0A%20%20%20%20%20%20name%3A%20%22My%20Name%22%2C%0A%20%20%20%20%20%20age%3A%2024%2C%0A%20%20%20%20%20%20gender%3A%20ladyboy%2C%0A%20%20%20%20%20%20contacts%3A%20%7B%0A%20%20%20%20%20%20%20%20email%3A%20%22mail%40example.com%22%2C%0A%20%20%20%20%20%20%20%20phones%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22111-222-333-444%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22444-555-666-777%22%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D)%20%7B%0A%20%20%20%20clientMutationId%0A%20%20%20%20nodeId%0A%20%20%20%20recordId%0A%20%20%20%20record%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20age%0A%20%20%20%20%20%20gender%0A%20%20%20%20%20%20contacts%20%7B%0A%20%20%20%20%20%20%20%20email%0A%20%20%20%20%20%20%20%20phones%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20)  [[code](https://github.com/nodkz/graphql-compose-examples/blob/master/examples/userForRelay/models/user.js#L41)]
