### ISSUE TITLE
Buffer input type for uploading images / multi-part

### ISSUE THREAD

**Issue by atalebagha** [nodkz/graphql-compose#41]
How can I create an GraphQL InputType that uploads images (via firebase or aws)

```javascript
const ImageSchema = new Schame({
  fileName: String,
});

const Image = mongoose.Schema('Image', ImageSchema);

const ImageTC = composeWithRelay(composeWithMongoose));
```

How do I add an input field which would be a buffer and upload the image, the image then get's sent to firebase/aws and the string is stored into the datastore.

Thanks!

**Comment by nodkz** [comment]
Sorry, I have not proper example for you. In my internal app I create signed upload url for aws s3, upload file and send via mutation only url. I did not play with Buffer type.

More details can be found here: https://devcenter.heroku.com/articles/s3-upload-node

PS. If you realize uploading via Buffer type. Please share your solution for future googlers. Thanks.

**Comment by stoffern** [comment]
@atalebagha right now i am using a seperate express route to handle the file upload part.
Altho both GraphQL and graphql-compose can handle this.
I will add my working example when i have rewritten the upload part.
(that is when i am complete with the app 😉 )

https://medium.com/@danielbuechele/file-uploads-with-graphql-and-apollo-5502bbf3941e#.f0okkdlgr

**Comment by yoadsn** [comment]
I am lazy compared to @stoffern and @nodkz  - I use Cloudinary's services to upload files and do all image retrieval and manipulation. They take care of **everything** (and I need to pay good money for that.. but saved me tons of time and grief for now).

**Comment by nodkz** [comment]
Also this comment may be useful: https://github.com/graphql/express-graphql/issues/9#issuecomment-143331902

**Comment by atalebagha** [comment]
Thanks! all.  I actually am doing what @nodkz recommended, and that is to upload directly to amazon
