### ISSUE TITLE
[$updateById] - updating to a dupe key

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose#42]
Returns error when updating a field to a value that already exists when key is set to unique.
Mongo will report back error msg but it will not be handled correct. 
(Only tested using Relay)

**Comment by nodkz** [comment]
As I see https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/resolvers/updateById.js#L94-L122 all errors from mongoose/mongodb should be thrown up via Promise.

Did you receive error on the client?
If graphql-server returns to you an error, so it's good (expected behavior). You need wrap resolver with catching this error.

Or maybe I do not understand problem?...

**Comment by stoffern** [comment]
GraphQL returns error:
```js
{
  "data": {
    "userUpdate": null
  },
  "errors": [
    {
      "message": "E11000 duplicate key error collection: database.Users index: email_1 dup key: { : \"test@test.com\" }",
      "locations": [
        {
          "line": 1,
          "column": 17
        }
      ],
      "path": [
        "userUpdate"
      ]
    }
  ]
}
```

Relay on the client side throws error and crashes the app:
```
Console.error: [RELAY-NETWORK] GRAPHQL SERVER ERROR: "E11000 duplicate key error collection: database.Users index: email_1 dup key: { : \"test@test.com\" }"
```

**Comment by nodkz** [comment]
Too strange. In my app I use `E11000` on the client for checking duplicates and all works properly without crash. 

Did you use `onFailure` callback?
```js
      Relay.Store.commitUpdate(
        new CreateUserMutation({
          ...formData,
        }),
        {
          onSuccess: () => {
            this.setState({
              isSaving: false,
              isSubmited: true,
              errMsg: null,
            });
          },
          onFailure: (transaction) => {
            const e = transaction.getError();
            let errMsg = e ? e.message.toString() : null;
            if (/E1100/.test(errMsg)) {
              errMsg = 'You data submitted already.';
            }
            this.setState({
              isSaving: false,
              errMsg,
            });
          },
        }
      );
```
