### ISSUE TITLE
[Feature] Add ability to pass fieldConfig to `addRelation` method.

### ISSUE THREAD

**Issue by nodkz** [nodkz/graphql-compose#43]
`TypeComposer.addRelation` is a good solution for solving hoisting problem. It's defined via arrow function and converted to the field with config in `GQC.buildSchema` method. 

Eg. in AuthorTC you relate PostTC and in PostTC you add AuthorTC (you may get as undefined first or second TC). So methods like `setFields` can not solve this problem, but `addRelation` does.

Right now `addRelation` works only with `Resolver`, for example:
```js
// author.js
AuthorTC.addRelation(
  'posts',
  () => ({
    resolver: PostTC.get('$findMany'),
    args: {
      filter: source => ({ authorId: source._id }),
    },
    projection: { _id: 1 },
  })
);

// post.js
PostTC.addRelation(
  'author',
  () => ({
    resolver: AuthorTC.get('$findById'),
    args: {
      _id: source => source.authorId,
    },
    projection: { authorId: 1 },
  })
);
```

But in some cases, will be useful to pass `fieldConfig` directly to the relation. For one time using it's too dirtily to define `Resolver`, too much typing.
So let's allow to pass `fieldConfig` to the `addRelation` method. Eg.
```js
// author.js
AuthorTC.addRelation(
  'hottestPost',
  () => ({
    type: PostTC,
    resolve: (source, args, context, info) => {
       const authorId = source._id;
       return PostModel.findFromSomeMongooseStaticMethod(authorId);
    },
    projection: { _id: 1 },
  })
);
```

To avoid errors Resolve thunk will check a presence of `resolver` property and absence of `type` and `resolve` properties and vice versa at the build schema step.

**Comment by yoadsn** [comment]
Thanks for that - I had the same thought a while back and was not sure why "addRelation" is not the only thing we need (instead of using addField).
Is there really something addRelation is not meant to do that addField does?

**Comment by nodkz** [comment]
@yoadsn sorry, but I did not understand your question.

**Comment by yoadsn** [comment]
Wondering - What is the purpose of `addField` when `addRelation` can do all it's jobs (and better)?

**Comment by nodkz** [comment]
`addField` used widely in plugins of graphql-compose. Via addField/setField you field immediately set to the fields of GraphQL type. So you may read them, use `.get('path.to.sub.field')` method, may use `extendField` method (change field config). In common write series of helper methods that tune/build your type.

Eg. for one mongoose model created one main type and about 50 subtypes for resolvers, args. So all them created via addField/setField step by step with adding/cloning/removing/updating. 

----

`addRelation` it's delayed addition field to the GraphQL type via function. And will be called/converted_to_field on `GQC.buildSchema` call, or when you explicitly call TC.buildRelations().

It useful when you connect different main types (your mongoose models) with each other and may got hoisting problem.
