### ISSUE TITLE
Adding auth to fields

### ISSUE THREAD

**Issue by joepistritto** [nodkz/graphql-compose#44]
Hi, thanks again for awesome library. I am new to GraphQL so still learning. I have the following schema:

```js
const UserSchema = new Schema({
  name: String,
  secret: String
});
```

Lets say I create a UserTC from this schema and I want the `secret` field to only be displayed if the logged in user (stored in `req.user` as in `req.user.id == user._id`), how do I do that? Is there a way to wrap the fields of UserTC so that whenever `secret` is accessed, I can check the req object so see if it should return it or return null instead?

**Comment by joepistritto** [comment]
ok, I see you can use extendField to do this. Closing.

**Comment by nodkz** [comment]
Yep, you may use this method:
```js
UsersTC.extendField('businessRole', {
  description: 'May see only admins',
  resolve: (source, args, context) => (context.isAdmin ? source.businessRole : null),
});
```
-----------
But in case, when you need compare value from request with a document field which not in query, you may add projection
```js
UsersTC.extendField('businessRole', {
  description: 'May see only admins',
  resolve: (source, args, context) => (context.user === source._id ? source.secret : null),
  projection: { _id: 1 }
});
```

So for query 
```
query {
  user {
    secret
  }
}
```
will be requested `secret` and `_id` field from DB. PS `_id` field is not good example, case mongodb returns it by default. But for other fields it will be useful (fetch them from DB, if they a not present in query).
