### ISSUE TITLE
List/Array of Type

### ISSUE THREAD

**Issue by atalebagha** [nodkz/graphql-compose#45]
I am creating an addResolver and one of the args is a list of `OtherSchema`:
```javascript
import OtherModelTC from './Schema'

...

ThisModelTC.addResolver({
  name: 'Resolver',
  type: 'mutation',
  args: {
    otherModel:  [OtherModelTC]
  }
})
```
How do I set that up?  I'm getting errors if I wrap it within brackets

Thanks

**Comment by nodkz** [comment]
I know that somebody will need it.
Exactly for you 😉 6 day ago landed `TC.getTypePlural()` method.

```js
ThisModelTC.addResolver({
  name: 'Resolver',
  type: 'mutation',
  args: {
    otherModel:  OtherModelTC.getTypePlural(),
  }
})
```

PS. I don't check Array object type. Maybe in future add this ability. But there are too many checks on types provided for graphql type field and adding `[TC]` may relax checks on the build.

**Comment by nodkz** [comment]
FYI your task may be solved with more typing in such way:

```js
import { GraphQLList, GraphQLNonNull } from 'graphql';

ThisModelTC.addResolver({
  name: 'Resolver',
  type: 'mutation',
  args: {
    otherModel:  new GraphQLNonNull(new GraphQLList(OtherModelTC.getType())),
  }
});
```

Right now `TypeComposer` does not have `GraphQLNonNull` helpers. But `Resolver` has [methods](https://github.com/nodkz/graphql-compose/blob/master/src/resolver.js#L125) `makeRequired` and `makeOptional` methods.

**Comment by yoadsn** [comment]
@nodkz just needed the same thing two days ago :)
Thanks to the new docs I found about the `getTypePlural` method and used it. Now seeing this issue, I think it can be resolved.
