### ISSUE TITLE
Add ability to set a defaultValue in the InputTypeComposer

### ISSUE THREAD

**Issue by aneilbaboo** [nodkz/graphql-compose#48]
A method that would allow setting a defaultValue for a specific field.  E.g.,

```javascript
var MyType = new GraphQLObjectType({
  name: 'MyType', 
  fields: { 
    flag: { type: GraphQLBoolean },
    value: { type: GraphQLString } 
  }
);
var tc = new TypeComposer(MyType);
var itc = tc.getInputTypeComposer();
itc.setDefaults({ flag: true, value: 'mydefaultvalue' });
```

**Comment by nodkz** [comment]
@aneilbaboo good catch!

Right now you may setup default values in such way:
```js
var itc = tc.getInputTypeComposer();
itc.setField('flag', { ...itc.getField('flag'), defaultValue: true });
itc.setField('value', { ...itc.getField('flag'), defaultValue: 'mydefaultvalue' });
```
But it's very monstrous. Should be simplified.

----
### 1st solution is 
**...an addition of method `extendField(name: string, parialFieldConfig: GraphQLInputFieldConfig)` to InputTypeComposer. Analogious solution has [typeComposer](https://github.com/nodkz/graphql-compose/blob/master/src/typeComposer.js#L184-L191) already.**

Definitely, it will be realized in next version of `graphql-compose`. If you want to make such PR, drop a comment. Or I will do it in a couple of days when will have free time.

With this method your problem will be solved in such manner:
```js
var itc = tc.getInputTypeComposer();
itc.extendField('flag', { defaultValue: true });
itc.extendField('value', { defaultValue: 'mydefaultvalue' });
```

### 2nd solution is 
**...an addition your method `setDefaults` to the InputTypeComposer.**
I looked at ITC source code, and think that this method will be more useful than polluting the API. In favor of more comfortable definition and less typing:
```js
var itc = tc.getInputTypeComposer();
itc.setDefaults({ flag: true, value: 'mydefaultvalue' });
```
1. But what you think about more clear name `setDefaultValues`?
2. And what about removing default values (how it can be done)? In such way `itc.setDefaultValues({ flag: undefined });` or should be more obvious `itc.removeDefaultValue('flag', /* or array of fields ['flag', 'value'] */);`

Thoughts @aneilbaboo @stoffern @yoadsn?

**Comment by aneilbaboo** [comment]
Nice solution, thank you

**Comment by yoadsn** [comment]
@nodkz 1st solution makes the most sense to me.
I don't think the verbosity of "setDefaultValues" is worth the API complexity increase. Extending with an override configuration is more reusable and in a sense even more readable since the input for SetDefaultValues has to specify field names as keys which may or may not exist. At least extending a field has a semantic which is more strict about which field are you referring to.

**Comment by nodkz** [comment]
@yoadsn thanks very helpful

**Comment by stoffern** [comment]
i completely agree with @yoadsn 😉

**Comment by nodkz** [comment]
Thanks for conversation @aneilbaboo @stoffern @yoadsn

I'll implement only 1st solution, keeping API slim.
```js
var itc = tc.getInputTypeComposer();
itc.extendField('flag', { defaultValue: true });
itc.extendField('value', { defaultValue: 'mydefaultvalue' });
```

**Comment by nodkz** [comment]
Bumped v1.13.0

**Comment by aneilbaboo** [comment]
Looks great.  I like solution 1 also.
