### ISSUE TITLE
[Feature] commitizen & semantic release

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose#5]
Add commitizen and semantic release for automatic versioning and NPM releasing.

- [x] commitizen
- [x] semantic-release

**Comment by nodkz** [comment]
Thanks for the links. Super cool.
Both of them new for me, need to find time to play with them.

**Comment by nodkz** [comment]
@stoffern did you setup `changelog.md` autogeneration? 
I do not solve this via trial and error way. 😝

**Comment by stoffern** [comment]
@nodkz no, i did not setup changelog.md usually release notes covers it all 😉

**Comment by nodkz** [comment]
Angular repo has Changelog.md, other good oss repos also have it. So I'll setup it when I get back from vacation.
