### ISSUE TITLE
Who wants to speak about graphql-compose on GraphQL-Europe conference?

### ISSUE THREAD

**Issue by nodkz** [nodkz/graphql-compose#51]
https://graphql-europe.org/
Berlin, May 21st, 2017

Try to find somebody who can/want to speak on GraphQL-Europe about `graphql-compose`. I do not speak English very well and can not be as a speaker. So with pleasure help that man who have enough experience with `graphql-compose` and use it in their app.

Please hurry up, CFP closes on: March 31, 2017 06:00
https://www.papercall.io/graphql-europe

**Comment by stoffern** [comment]
I would love to do it, but i dont have the time 😞 
If someone need any examples i can provide..

**Comment by yoadsn** [comment]
Same here - Would not be able to fly out all the way to Europe... (no $$)

**Comment by nodkz** [comment]
@yoadsn I suppose they cover expenses on flight/hotel for speakers.
Asked here: https://twitter.com/nodkz/status/844199923537076224

**Comment by nodkz** [comment]
Nope, GraphQL-Europe does not cover expenses on flight/hotel for speakers.

<img width="584" alt="screen shot 2017-03-22 at 14 30 18" src="https://cloud.githubusercontent.com/assets/1946920/24188604/34e0aa0a-0f0c-11e7-9e3b-63124b412b13.png">


So chances that talk about `graphql-compose` will be on GraphQL-Europe almost equal to zero. `Graphql-compose` are truly OSS without sponsors and not covered by any company.

**Comment by yoadsn** [comment]
@nodkz I checked again with my partner.. Not this time - sorry.
