### ISSUE TITLE
addFilterArg with a Boolean value

### ISSUE THREAD

**Issue by yoadsn** [nodkz/graphql-compose#57]
Tried to create a filter with an `$exists` operator. Used the following:
```
tc.get('$findMany')
.wrapCloneArg('filter', 'FilterFindManyWithExists')
.addFilterArg({
  name: `externalUrlExists`,
  type: 'Boolean',
  query: (query, value, resolveParams) => {
    query.externalUrl = { $exists: value }
  }
});
```

This would not work when the query filters by a `false` value like so:
```
query {
 entities(filter: { externalUrlExists: false }) {
   someField
  }
}
```

The reason is due to how the `resolve` is wrapped [here](https://github.com/nodkz/graphql-compose/blob/bdc1d5e942ef1e8c828708286a5c1c37bb4588dd/src/resolver.js#L498-L503)

The existence of the value is checked with a simple boolean test which prevents a boolean false to pass as a value.

Before I jump into trying to fix this - Is there any reason the condition would not be
```
if (typeof value === 'undefined')
```
?

Btw, a workaround until we improve this is to use a String type for example:
```
tc.get('$findMany')
.wrapCloneArg('filter', 'FilterFindManyWithExists')
.addFilterArg({
  name: `externalUrlExists`,
  type: 'String',
  query: (query, value, resolveParams) => {
    query.externalUrl = { $exists: value != 'false' }
  }
});
```
And pass "true" and "false" in the query filter. :shit:

**Comment by nodkz** [comment]
Fill free to change it on `value!==null && value!== undefined`.
Defenetly false should be passed. About passing null I'm not sure, so let keep it (do not remember how input vars works, from mobile now and closer 3 weeks). And undefined should be skipped.
