### ISSUE TITLE
Promoting maximum call stack size exceeded when the query is a little bit complex

### ISSUE THREAD

**Issue by andersonlin** [nodkz/graphql-compose#62]
Hello Pavel,

I really appreciate this project that empowers me to use GraphQL in really project, but I came to the following issue when the query is a little bit complex.

`"errors": [
    {
      "message": "Maximum call stack size exceeded",
      "stack": [
        "RangeError: Maximum call stack size exceeded",
        "    at String.startsWith (native)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:45:13",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)"
      ]
    },
    {
      "message": "Maximum call stack size exceeded",
      "stack": [
        "RangeError: Maximum call stack size exceeded",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:45:13",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7",
        "    at Array.forEach (native)",
        "    at toMongoDottedObject (/Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:44:28)",
        "    at /Users/andersonlin/Git/graphql/api-demo/node_modules/.1.4.9@graphql-compose-mongoose/lib/utils/toMongoDottedObject.js:48:7"
      ]
    }
  ]`

many thanks!

**Comment by stoffern** [comment]
You have a loop error..
Please check your code or provide code or a repo..

**Comment by nodkz** [comment]
@andersonlin according to this code
https://github.com/nodkz/graphql-compose-mongoose/blob/master/src/utils/toMongoDottedObject.js#L28 and provided error you may use recursive objects in the query. Something like this:
```js
const a = {};
const b = {};
a.b = b;
b.a = a;
console.log(JSON.stringify(a)); // also produce error
```
<img width="259" alt="screen shot 2017-06-02 at 17 10 17" src="https://cloud.githubusercontent.com/assets/1946920/26723500/926057d8-47b6-11e7-8a3e-38171022aed6.png">
<img width="435" alt="screen shot 2017-06-02 at 17 11 11" src="https://cloud.githubusercontent.com/assets/1946920/26723504/95d76280-47b6-11e7-843a-a0055eaa96a2.png">


If you use circular structure in the query, then this error should be, because I don't know how to convert such type of object in the dotted form.

**Comment by andersonlin** [comment]
hello @nodkz @stoffern 

Many thanks for your help!!

I am sorry for my mistake when writing the filter for an array, which should be $in instead of $eq.
* wrong: ~~filter: (source) => ({ _id: source.comments }),~~
* correct: filter: (source) => ({ _id: { $in: source.comments } }),

the correct code as following:
```javascript
EventTC.addRelation(
  'commentConnection',
  () => ({
    resolver: CommentTC.getResolver('findMany'),
    args: {
      filter: (source) => ({ _id: { $in: source.comments } }),
    },
    projection: { comments: true },
  })
);
```
