### ISSUE TITLE
wrapCloneArg for a GraphQLNonNull wrapped arg fails

### ISSUE THREAD

**Issue by yoadsn** [nodkz/graphql-compose#68]
I wonder if this is by design.
I was trying to wrap a resolver of a mutation which had a single required parameter. (`createOne` from `graphql-compose-mongoose`).
I wanted to remove fields from that parameter and so did:

```
let newResolver = SomeTC.get('$createOne').wrapCloneArg('record', 'SomeNewInput')
.wrap(...) // more changes to the resolved
```
And then got this error:
```
Error: Can not clone arg record for resolver cloneFilterArg.Argument should be GraphQLInputObjectType (complex input type).
```

I believe this is due to the checks [here](https://github.com/nodkz/graphql-compose/blob/8a9cd5ccdd0b5465e5eac361a712674921cc51f9/src/resolver.js#L166-L171) and the intention was to make sure a complex Input type is cloned.

Should we try and flex this limitation to maybe unwrap/wrap the internal type in case it is wrapped in a `GraphQLNonNull` type? Or is there any reason such args should not be cloned?

**Comment by nodkz** [comment]
Unwrap/wrap with `GraphQLNonNull` will be very useful. 
Can you make PR?

BTW. If you need to make it optional, you may use `makeOptional` method:
```js
SomeTC.getResolver('createOne').wrapCloneArg('record', 'SomeNewInput').makeOptional('record').wrap(...)
```

**Comment by nodkz** [comment]
PS. Also I do not recommend to use magic method `.get('$createOne')`. If you want to cover your code with flowtype in future. Better will be `getResolver('createOne')` it will return only `Resolver` type and autocompletion will provide to you resolvers methods. And flow will make more strict checks.

**Comment by yoadsn** [comment]
@nodkz I'll work on this PR.
I did not want to make it optional - it should remain mandatory but without a specific field filled by the authentication context.
