### ISSUE TITLE
extendField after addRelation

### ISSUE THREAD

**Issue by joepistritto** [nodkz/graphql-compose#72]
I have a type-composer that I added a field to using addRelation:

```
MyTypeTC.addRelation('field1', { resolver: () => ...})
```

I then want to extend it:

```
MyTypeTC.extendField('field1', { resolve: (source, args, req) => { ... } })
```

I get an error:

```
Error: MyType.field1 provided incorrect OutputType: '{}'
```

It seems after the call to addRelation, the field is not properly set up yet? I find that if I call ```GQC.buildSchema()``` between the ```addRelation``` and ```extendField``` it works. Is that what is recommended?

**Comment by nodkz** [comment]
Add checks for such case. Now will throw such error:
```
Cannot extend field 'field1' from type 'MyType'. FieldConfig declared as a function.
Such declaration helps to solve hoisting problems between two types which import each other'
```

It means that you can not extend fields which were declared via `addRelation`. Commonly relations created between two types and may be such situations where types import each other and may bring hoisting problem (when variable/module not defined yet but already called for type construction).

---

I do not recommend call `GQC.buildSchema()`. But you may do it. Be careful, in future I may deprecate `buildSchema` method. But will be provided some workaround for it.

Better to construct relation only once and do not modify/extend it. But you may completely replace it by new config if needed.

How I see you try to modify `resolve` behavior of Resolver. And it can be done via `Resolver.wrapResolve` method. `wrapResolve` creates new resolver (keep default resolver untoched) which can be provided as field config. Eg:

```js
MyTypeTC.addRelation('field1', {
  resolver: () => OtherTC.getResolver('findOne').wrapResolve(next => rp => {
    const { isAdmin } = rp.context;
    if (!isAdmin) return null;
    return next(rp);
  }),
});
```
A little bit more about `wrapResolve`:
https://github.com/nodkz/graphql-compose-mongoose/issues/33#issuecomment-305415238
https://github.com/nodkz/graphql-compose/tree/master/docs/06-advanced

**Comment by nodkz** [comment]
Close this issue, cause nothing to do with lib.

But feel free to continue the discussion if you have questions according to your problem.
