### ISSUE TITLE
Sort not working

### ISSUE THREAD

**Issue by akaNightmare** [nodkz/graphql-compose#76]
Hello,
GraphiQL:
http://screenshots.client-demo-site.net/scn-20170814-225232-egueu.png
http://screenshots.client-demo-site.net/scn-20170814-225336-hl9tc.png

MongoDB queries:
http://screenshots.client-demo-site.net/scn-20170814-225425-ross9.png

GraphQL query:
http://screenshots.client-demo-site.net/scn-20170814-225522-6hyrb.png

**Comment by nodkz** [comment]
Added new tests to [graphql-compose-pagination](https://github.com/nodkz/graphql-compose-pagination/commit/4b9953cca687fcc7ea6fbef73140d96532420991). All works as expected.

Live test queries also [correctly works](http://graphql-compose.herokuapp.com/user/?query=%0A%7B%0A%20%20ascSortingTestByAge%3A%20userPagination(filter%3A%20%7B%20gender%3A%20male%20%7D%2C%20perPage%3A%202%2C%20page%3A%201%2C%20sort%3A%20AGE_ASC)%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20age%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20descSortingTestByAge%3A%20userPagination(filter%3A%20%7B%20gender%3A%20male%20%7D%2C%20perPage%3A%202%2C%20page%3A%201%2C%20sort%3A%20AGE_DESC)%20%7B%0A%20%20%20%20items%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20age%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20).

It seems that a problem somewhere in your code. Can you provide demo repo?

**Comment by akaNightmare** [comment]
@nodkz sorry for false alarm, I forgot add sort param into graphql query on client side
