### ISSUE TITLE
[Question] Master detail like relay example

### ISSUE THREAD

**Issue by richyeiv** [nodkz/graphql-compose#8]
Working with the schema defined in #2 and with the following defined:
```
export default class extends Relay.Route {
  static queries = {
    viewer: () => Relay.QL`
      query {
        viewer 
      }
    `
  };
```
In app.js
```
ReactDOM.render(
  <Relay.Renderer
    environment={Relay.Store}
    Container={App}
    queryConfig={new AppHomeRoute()}
  />,
  document.getElementById('root')
);
```

In components/App.js 
```
class App extends React.Component{
   let list = this.props.viewer.dmcConnection.edges.map((edge, idx) => 
      <li key={idx}>{edge.node.name}</li>
    );
    render(){
        return(
        <div>
            <ul>
                {list}
            </ul>
        </div>
        );
    }
}

export default Relay.createContainer(App, {
  initialVariables: {
    limit: 100
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
          dmcConnection(first: $limit) {
            edges{
              node{
                name
              }
            } 
          }        
      }
    `,
  },
});
```

When I click on a li I want to show another component with the detail of dmc object. How can I start?
Feel free to close this if you consider it's irrelevant.
Thank you as always.

**Comment by nodkz** [comment]
How I understand you want to do it not via `react-relay-router`. I add data to Store via `relayStore.primeCache()` method.

See how it works in `relay-northwind-app` with category toggling:
- **ToggleCategory.js:** https://github.com/nodkz/relay-northwind-app/blob/master/app/components/categories/ToggleCategory.js
- **Product.js:** https://github.com/nodkz/relay-northwind-app/blob/master/app/components/products/Product.js#L33
- **Live demo:** https://nodkz.github.io/relay-northwind/#/products?_k=dkvuyr
