### ISSUE TITLE
Keep the "filter" arg with an addRelation() that prepares that filter arg

### ISSUE THREAD

**Issue by toverux** [nodkz/graphql-compose#94]
My relation looks like this:

```typescript
tc.addRelation('lots', {
    resolver: () => lotTypeComposer.getResolver('findMany'),
    prepareArgs: {
        filter: (source: IProject) => ({ project: source._id.toString() })
    }
});
```

That works well, but I loose the `filter` arg originally provided by `findMany` from graphql-compose-mongoose.

I don't see a simple way to generate a new _filter_ arg and add it again to the schema, in order to be able to filter on the "sub query". Am I wrong? :)

Thanks in advance!

**Comment by nodkz** [comment]
Yep, now keeping `filter` arg in relations is not solved task. It required creation of new input type for `filter`, where should be removed `project` field, cause you set it up already. And allowing to modify this arg is not good via query. Also is not good to show `project` field in schema introspection, and do not process it if user set some value via query for this field.

I'm open to suggestions how it can be implemented.

---

But for now, you may do what you want is such manner:
```js
const findManyResolver = lotTypeComposer.getResolver('findMany');
tc.addFields({
  lots: {
    type: findManyResolver,
    args: findManyResolver.getArgs(),
    resolve: (source, args, context, info) => {
      return findManyResolver.resolve({
        source, args, context, info,
        rawQuery: {
          project: source._id.toString(),
        },
      });
    },
    projection: {
      // do not forget use projection 
      // when you request just `lots` field graphql-compose 
      // will automatically request `project` field from database for `source`
      // which is required for correct relation call
      project: true,
    }
  }
});
```

**Comment by toverux** [comment]
Oh, thank you, I didn't thought about doing without `addRelation()`... (and thank you too for catching the missing `projection`).

However I get another problem with that solution: the _lots_ file has circular dependency with the _projects_ file. The code that is at top-level can't access the contents of lotTypeComposer (that comes from an import from the other file) - I use Webpack.

In the previous example I was doing:

```typescript
tc.addRelation('lots', {
    // the dot-access on lotTypeComposer is proxied behind a function
    resolver: () => lotTypeComposer.getResolver('findMany'),
```

But the `args` option of `addFields()` can't take a function:

```typescript
tc.addFields({
    lots: {
        type: () => lotType.getResolver('findMany'), // ok
        args: () => lotType.getResolver('findMany').getArgs(), // compile error and no args at runtime
```

The import:

```typescript
import { typeComposer as lotTypeComposer } from './graphql-lot';
```

**Comment by nodkz** [comment]
Try `lots: () => ({ type, args, resolve })`. Wrap field config in arrow function.

Answered from phone.

**Comment by nodkz** [comment]
Field config can be defined as a function.

So my first example can be improved in such way for solving hoisting (circular dependency) problem:
```js
const findManyResolver = lotTypeComposer.getResolver('findMany');
tc.addFields({
  lots: () => ({  // <--- wrap fieldConfig with arrow function
    type: findManyResolver,
    args: findManyResolver.getArgs(),
    resolve: (source, args, context, info) => {
      return findManyResolver.resolve({
        source, args, context, info,
        rawQuery: {
          project: source._id.toString(),
        },
      });
    },
    projection: {
      project: true,
    }
  })
});
```

**Comment by toverux** [comment]
Yay, that works!
At least at runtime :smile: Type-checking fails because fields of `addFields()` aren't permitted to be callables.
See https://github.com/nodkz/graphql-compose/blob/master/src/typeComposer.d.ts#L18

I based myself on the commented Flow types here https://github.com/nodkz/graphql-compose/blob/master/src/typeComposer.js#L69

Maybe they are not up-to-date. Should we simplify the TypeScript version to match the actual Flow version? https://github.com/nodkz/graphql-compose/blob/master/src/typeComposer.js#L63

**Comment by nodkz** [comment]
Nope, there are flow type problems, that is why it casted to any.
I did not check them in latests flowtype versions, maybe it already works.

Just try to add Thunk to ComposeFieldConfig:
https://github.com/nodkz/graphql-compose/blob/master/src/typeComposer.d.ts#L24-L31

```js
export type ComposeFieldConfig<TSource, TContext> = 
  ... | Thunk<ComposeFieldConfig<TSource, TContext>>;
```

If it works without errors, then open PR.

**Comment by toverux** [comment]
Yep, however `ComposeFieldConfig` can't reference itself like this (I mean, the language doesn't like that :smile:). We need to declare de Thunk variant in the type that uses it:

```diff
export type ComposeFieldConfigMap<TSource, TContext> = {
    [fieldName: string]:
        | ComposeFieldConfig<TSource, TContext>
+       | Thunk<ComposeFieldConfig<TSource, TContext>>
        | Array<ComposeFieldConfig<TSource, TContext>>
+       | Thunk<Array<ComposeFieldConfig<TSource, TContext>>>
        | GraphQLFieldConfig<TSource, TContext>,
} | GraphQLFieldConfigMap<TSource, TContext>;
```

Just not sure about the `Array<ComposeFieldConfig<>>` one, is it thunkable too?

**Comment by nodkz** [comment]
`Thunk<Array<ComposeFieldConfig<TSource, TContext>>>` is correct.
But you miss `GraphQLFieldConfig<TSource, TContext>`, it also can be an Array.

**Comment by toverux** [comment]
Oh, okay, it was likely absent from the flow version. I presume it's thunkable too then.
Will open the PR today if possible!

**Comment by toverux** [comment]
Closing this issue as the original problem is solved. Thanks again!

**Comment by synthecypher** [comment]
Referencing my [example](https://github.com/graphql-compose/graphql-compose/issues/94#issuecomment-334407558) of creating a new input type that removes the related ID field. As this is controlled by the relation and should not be queryable in the `filter`.
